#! /bin/bash
LOG=$HOME/log.txt
RAW=$HOME/raw.txt
SOURCE="$@"
$SOURCE &>$RAW & pid=$!
pid_exists() {
pid="$1"
test -n "$pid"
echo "$pid"|wc -w|grep -q "^1$"
test -d /proc/$pid
}
stamp() {
len=$1
newlen=$2
len1=$(($len + 1))
for n in $(seq $len1 $newlen); do
DATE="$(date +%s%N)"
LINE="$(cat $RAW|head -n $n|tail -n 1)" || true
test -n "$LINE" && echo "$DATE	$LINE" >>$LOG
done
}
len=0
while pid_exists $pid; do
newlen=$(cat $RAW|wc -l)
if [ $newlen -gt $len ]; then
stamp $len $newlen
len=$newlen
fi
sleep 0.02
test -d /proc/$pid || break
done
